services:
  frontend:
    build:
      context: ./sistema_encuestas_frontend_inicial
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./sistema_encuestas_frontend_inicial:/app
    restart: always
    command: sh -c "npm install && npm run build && npm start"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:8000
      - NODE_OPTIONS=--openssl-legacy-provider
    networks:
      - app-network
    depends_on:
    - backend
    
    

  backend:
    build:
      context: ./sistema_encuestas_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/Encuestas_py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
