version: '3.8'

services:
  frontend:
    build:
      context: ./sistema_encuestas_frontend_inicial
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network

  backend:
    build:
      context: ./sistema_encuestas_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 