version: '3.8'

services:
  # =====================================================
  # BASE DE DATOS - POSTGRESQL
  # =====================================================
  db:
    image: postgres:15-alpine
    container_name: encuestas_db_local
    restart: unless-stopped
    environment:
      POSTGRES_DB: sistema_encuestas
      POSTGRES_USER: sc_admin_user_42
      POSTGRES_PASSWORD: NuevaClave123!
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"  # Accesible desde localhost para pruebas
    networks:
      - encuestas_net_local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sc_admin_user_42 -d sistema_encuestas"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =====================================================
  # BACKEND - FASTAPI
  # =====================================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encuestas_backend_local
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://sc_admin_user_42:NuevaClave123!@db:5432/sistema_encuestas
      - SECRET_KEY=clave-secreta-muy-larga-y-segura-para-backend-123456789
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - GOOGLE_CLIENT_ID=test-client-id
      - GOOGLE_CLIENT_SECRET=test-client-secret
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=plazadedatoscom@gmail.com
      - EMAIL_HOST_PASSWORD=Plazadedatos226118*/
      - DEFAULT_FROM_EMAIL=plazadedatoscom@gmail.com
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001
      - NOMBRE_SISTEMA=Sistema de Encuestas con Recompensas
      - VERSION=1.0.0
      - DEBUG=true
      - NODE_ENV=development
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "8000:8000"  # Accesible desde localhost para pruebas
    networks:
      - encuestas_net_local
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

# =====================================================
# VOLUMENES
# =====================================================
volumes:
  postgres_data_local:
    driver: local
  uploads:
    driver: local
  logs:
    driver: local

# =====================================================
# REDES
# =====================================================
networks:
  encuestas_net_local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16 